# from: https://gist.github.com/DewaldDeJager/518f6814049a0f7763642ec02f62cabf

name: sync-fork
on:
  schedule:
    - cron: '21 3 * * 1'
  workflow_dispatch: { }
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: gh repo sync --force $REPOSITORY --branch $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}
